name: Release Candidate
on: 
  push:
    branches-ignore:
      - master
jobs:
  package:
    runs-on: [x64, self-hosted,linux,build]
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - name: Package
        id: package
        uses: AutoModality/action-package-debian-ros@v5-amros
        with:
          version: 1.13.0-AM${{ github.run_number }}
          release-repo-entitlement: ${{ secrets.CLOUDSMITH_READ_RELEASE_ENTITLEMENT }}
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
      - name: Deploy
        id: deploy
        uses: AutoModality/action-cloudsmith@0.2.0
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'deb'
          owner: 'automodality'
          repo: 'dev'
          distro: 'ubuntu'
          release: 'bionic'
          file: '${{ steps.package.outputs.artifact-path }}'
  package-cuda:
    runs-on: [arm64,self-hosted,linux, cuda]
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v2
      - name: CUDA Package
        run: |
          fakeroot debian/rules binary
          package_filename=$(ls *.deb | head -1)
          echo "::set-env name=PACKAGE_FILE::$package_filename"
      - name: Deploy
        id: deploy
        uses: AutoModality/action-cloudsmith@0.2.0
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'deb'
          owner: 'automodality'
          repo: 'dev'
          distro: 'ubuntu'
          release: 'bionic'
          file: '${{ env.PACKAGE_FILE }}'
